name: Electron forge build/release
run-name: ${{ github.actor }}
on: [push, workflow_dispatch]

jobs:
  release-electron-application:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:      
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
      
      - name: Publish MacOS electron release
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
          GITHUB_TOKEN: ${{ secrets.github_token }}
          
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_DATA }}
          P12_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run:
          sudo git config --system core.longpaths true
          
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/silverstock.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          
      - name: Publish Linux & Windows Electron release
        if: ${{ matrix.os  == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: npm run publish
