name: Electron forge build/release
run-name: ${{ github.actor }}
on: [push, workflow_dispatch]

jobs:
  release-electron-application:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
      
      - name: Publish MacOS electron release
        if: ${{ ${{ matrix.os }} == 'macos-latest' }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: node --version

      - name: Publish Linux & Windows Electron release
        if: ${{ ${{ matrix.os }} == 'ubuntu-latest' || ${{ matrix.os }} == 'windows-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: npm run publish
