name: Electron forge update/version
run-name: update-version
on:
  workflow_dispatch:

env:
  tag: ""

jobs:
  update-electron-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Update version
        run: |
          git config --global user.email "github@silver-smok.com"
          git config --global user.name "silver-smok-bot"
          npm version patch
          tag=$(git tag --points-at HEAD)
          git push origin "$tag"
          git push
          echo "TAG=$tag" >> "$GITHUB_ENV"
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          prerelease: true
