name: Electron forge update/version
run-name: update-version
on:
  workflow_dispatch:

env:
  tag: ""
  tagNoVersion: ""

jobs:
  update-electron-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Update version
        run: |
          git config --global user.email "github@silver-smok.com"
          git config --global user.name "silver-smok-bot"
          npm version patch
          tag=$(git tag --points-at HEAD)
          tagNoVersion="$tag" | sed 's/v//'
          echo "{\"name\":\"$tag\",\"notes\":\"New update\",\"url\":\"https://github.com/Silver-Smok/silverstock-electron-app/releases/download/$tag/SilverStock-darwin-x64-$tagNoVersion.zip\"}" > darwin-x64.json
          echo "{\"name\":\"$tag\",\"notes\":\"New update\",\"url\":\"https://github.com/Silver-Smok/silverstock-electron-app/releases/download/$tag/SilverStock-darwin-arm64-$tagNoVersion.zip\"}" > darwin-arm64.json
          echo "{\"name\":\"$tag\",\"notes\":\"New update\",\"url\":\"https://github.com/Silver-Smok/silverstock-electron-app/releases/download/$tag/SilverStock-win32-x64-$tagNoVersion.zip\"}" > win32-x64.json
          git add .
          git commit -m "Update version and updater files"
          git push origin "$tag"
          git push
          echo "TAG=$tag" >> "$GITHUB_ENV"
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          prerelease: true
