name: Electron forge update/version
run-name: update-version
on:
  workflow_dispatch:

env:
  tag: ""
  
jobs:
    update-electron-version:
        runs-on: ubuntu-latest
        
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js and NPM
              uses: actions/setup-node@v3
              with:
                node-version: "21"

            - name: Update version
              run: |
                git config --global user.email "github@silver-smok.com"
                git config --global user.name "silver-smok-bot"
                npm version patch
                tag=$(git tag --points-at HEAD)
                echo "$tag" >> "$GITHUB_OUTPUT"
                git push
                git push origin "$tag"
              id: tag_version

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: false
                automatic_release_tag: ${{ steps.tag_version.outputs.* }}
                title: ${{ steps.tag_version.outputs.* }}
